### ISSUE TITLE
error while injecting

### ISSUE THREAD

**Issue by ilikewwaffless** [IShade4Real/NetflixCE#5]
Im running windows 11.
its saying: Script Error
Error:C:\Users\user\Downloads\netflixce\autorun\roblox.lua:141: attempt to perform arithmetic on a nil value (local 'players')
stack traceback:
	C:\Users\user\Downloads\netflixce\autorun\roblox.lua:141: in function <C:\Users\sylwi\Downloads\netflixce\autorun\roblox.lua:93>
I am holding the tool while clicking inject.

**Comment by IShade4Real** [comment]
Dunno. never got this error.
Try re-installing NCE, re-joining via the baseplate game and not holding the tool while clicking inject (equip after inject successful)
If the error still occurs, read [troubleshooting](https://github.com/IShade4Real/NetflixCE?tab=readme-ov-file#troubleshooting-known-issues--fixes) page and [unlisted errors](https://github.com/IShade4Real/NetflixCE?tab=readme-ov-file#unlisted-errors) (make sure to include the Roblox version, ie: Web or UWP).

**Comment by chinkyuk** [comment]
Im also seeing this error

**Comment by IShade4Real** [comment]
try to run NCE via netflixprocesshandler.bat, that might fix it
if possible, provide me a video of you trying to inject and the error occuring
