### ISSUE TITLE
Character limit in internal exec?

### ISSUE THREAD

**Issue by num3raI** [IShade4Real/NetflixCE#9]
Seems there's a character limit in the internal exec, no way around it?

**Comment by IShade4Real** [comment]
Unfortunately nope

**Comment by num3raI** [comment]
Would I be able to make my own baseplate game? If I'm assuming that's how the preloaded scripts work.

**Comment by IShade4Real** [comment]
if you mean the baseplate game to use NCE, then for sure no. its gonna take a while you to script every single thing yourself. find a copy and then use it (yes you can, but make sure to enable 3rd party teleports or else itll keep giving out a error)

**Comment by num3raI** [comment]
Are there any copies of the baseplate game you know of floating around? Other than the one linked in this git, of course.
